---
abstract: 'Markdown as template body, no HTML.'
author:
  - 'Kang-min Liu, C<< <gugod at gugod.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Provider-Markdown
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Template: 2.2
  Text::Diff: 0
  Text::Markdown: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
